### ISSUE TITLE
annotation tempalte to fsaverage5

### ISSUE THREAD

**Issue by tanjia123456** [freesurfer/freesurfer#809] opened 2020-09-15 02:52 UTC
I have tried mri_label2label command
`mri_label2label  --srcsubject Afterthought-1  --srclabel Afterthought-1/label/rh.aparc.a2009s.annot  --trgsubject fsaverage5 --trglabel /home/tj/application/freesurfer/subjects/Afterthought-1-target/rh.aparc.a2009s.annot --hemi rh  --regmethod surface`

but error appears:mri_label2label.bin: could not scan # of lines from label file ERROR reading Afterthought-1/label/rh.aparc.a2009s.annot

what's the meaning of the error message? How to solve it?

**Comment by ahoopes** [comment] 2020-09-19 15:20
`mri_label2label` is specific to label files, not annotations. To map an annotation across surfaces, please see **example 6** in the help text for `mri_surf2surf`.

Closing as this is not a bug. If you have further questions, please post to the freesurfer mailing list.

**Closed as completed by ahoopes** 2020-09-19 15:20 UTC
