### ISSUE TITLE
make check fails since still expecting tcl under /usr/pubsw/packages/tcltktixblt/current/lib/tcl8.4

### ISSUE THREAD

**Issue by yarikoptic** [freesurfer/freesurfer#86] opened 2017-05-31 04:24 UTC
I did
```shell
./setup_configure && ./configure --prefix=/usr/local/freesurfer/dev --with-pkgs-dir=${PWD}/centos6-x86_64-packages --disable-Werror && make&& make check
```
which failed with fsgdf/test-suite.log containing

```
Trying: Tcl_Init returned not TCL_OK
Result: Can't find a usable init.tcl in the following directories: 
    /usr/pubsw/packages/tcltktixblt/current/lib/tcl8.4



This probably means that Tcl wasn't installed properly.

```
so I guess somewhere paths aren't yet adjusted to make use of with-pkg-dir where I do have `centos6-x86_64-packages/tcltktixblt/8.4.6/lib/tcl8.4`

**Comment by zkaufman** [comment] 2017-05-31 13:50
I believe this is a duplicate of this issue:

  https://github.com/freesurfer/freesurfer/issues/36

The problem is a hardcoded path somewhere in the tcltktixblt folder. For now the best solution is to just pass the `--disable--tcktk-apps` flags to the `./configure` script, since the tcltk tools are deprecated anyway and dont need to be built. Additionally, an environment variable could be set which skips the fsgdf test altogether (this approach is done with a few other tests as well).

**Comment by buildqa** [comment] 2018-10-22 22:00
I don't think this is an issue now given the build uses cmake with updated 3rd party package distributions.  Please see the new documentation on the cmake build, https://surfer.nmr.mgh.harvard.edu/fswiki/CMakePort    You can get the prebuilt archives of 3rd party packages from, http://surfer.nmr.mgh.harvard.edu/pub/data/fspackages/prebuilt/
So I will close this issue for now, but you can open a new issue if need be.

**Closed as completed by buildqa** 2018-10-22 22:00 UTC
