### ISSUE TITLE
orientation change after synthstrip 

### ISSUE THREAD

**Issue by wangyunai** [freesurfer/freesurfer#1025] opened 2022-10-06 17:22 UTC
Hi, 

I have a multi-side dataset. After using synthstrip, I observe the affine matrix is modified and not match to the output image. I wonder if anyone has similar issue ? 
Thanks! 

Yun

**Comment by loneblues** [comment] 2022-10-26 11:04
Hi. 

I probly have a similar issue, and I thought that it was due to not providing an image with whole brain coverage. 
The segmentation itself appears to be quite accurate, only it was shited. 
![image](https://user-images.githubusercontent.com/21212266/198010255-31ca3740-4cb7-4a07-9179-348e3a93515f.png)
![image](https://user-images.githubusercontent.com/21212266/198010302-90d906a6-0fff-4149-ac96-467d0f33a636.png)
Hope there is a way to walk around this issue. 

HJ

**Comment by mattcieslak** [comment] 2022-11-10 22:58
I've also seen this, the qform and sform end up with a mismatch in the images that are written out.

**Comment by mu40** [comment] 2022-11-15 13:15
The issue looks similar to https://github.com/freesurfer/freesurfer/issues/1015. Which SynthStrip are you using - do you observe this behavior for the most recent containerized version (https://w3id.org/synthstrip) or the FreeSurfer development distribution? If you do, is there any chance you could share the image?

**Comment by mattcieslak** [comment] 2022-11-15 13:41
I'm adding synthstrip to another docker image via a multistage build. here is how I get it:

```
COPY --from=freesurfer/synthstrip:1.2 /freesurfer/mri_synthstrip /opt/freesurfer/
COPY --from=freesurfer/synthstrip:1.2 /freesurfer/models/synthstrip.*.pt /opt/freesurfer/models/
```

here are the pre and post images:
[input_image.nii.gz](https://github.com/freesurfer/freesurfer/files/10013124/input_image.nii.gz)
[bad_header_output.nii.gz](https://github.com/freesurfer/freesurfer/files/10013126/bad_header_output.nii.gz)

**Comment by ahoopes** [comment] 2022-11-18 19:06
Sorry everyone for the delay in getting to this, but taking a look now.

As @mattcieslak pointed out, this seems to be related to the surfa library not saving the input qform and sform codes correctly. Based on those example images (thanks for sending), the actual voxel data of the output image should be correct and the underlying affine matrix is correct as well, so as long as your downstream tools don't rely on these codes in the nifti file (not sure how common that is outside of freesurfer), then this shouldn't cause problems beyond visualization.

What do you all use for visualizations? I use freeview, which ~~doesn't use the q/sform~~ (edit: it does, but handles missing data differently), so makes it tough to debug. Slicer doesn't seem to have a problem either, at least with the example data.

**Comment by mattcieslak** [comment] 2022-11-18 19:07
We use ITK snap, since this interprets image headers the same way as ANTs. You should see some upside-down brains when you open the examples in it

**Comment by ahoopes** [comment] 2022-11-18 19:14
Great thanks! I'll put a fix into surfa and rebuild a new synthstrip release - should only take a day or two, but I'll update here when it's available.

**Comment by dngreve** [comment] 2022-11-18 19:14
Freeview will use the qform if it is defined then the sform if no qform. In the FS C code, nifti images are usually written with both qform and sform and the sform=qform. I'm not sure how often tools use the sform, but probably good to have it there since it is part of the standard.

**Comment by ahoopes** [comment] 2022-11-18 19:19
OK thanks. Then I think in this particular case the issue is that qform isn't defined.

**Comment by ahoopes** [comment] 2022-11-19 17:41
Alright I updated surfa and made a new synthstrip container release (version 1.3). Could you let me know if this fixes the issue for you all?

If you're using the containers, you'll need to update the version numbers in the wrapper script headers to `1.3` (and for singularity you'll need to re-pull the image). You can also just re-download the scripts as it describes in the [docs](https://surfer.nmr.mgh.harvard.edu/docs/synthstrip).

If you're running synthstrip from a freesurfer release, the fix will take a couple days to get integrated into the development release, but a quick fix would involve updating the internal surfa version:

```
fspython -m pip install surfa==0.3.3
```

You might need to preface with `sudo -E` if it's installed as root.

**Comment by loneblues** [comment] 2022-12-02 07:24
Hi. Sorry for the late response. 
I ran Synthstrip 1.3 on the previously uploaded image. 
It appears that the issue is now fixed, at least on the data that I have. 
Many thanx!
![image](https://user-images.githubusercontent.com/21212266/205239240-893b00df-99a0-4395-9c9a-d7b85d6b2027.png)

**Closed as completed** 2022-12-21 14:24 UTC
