### ISSUE TITLE
What is the default template used by Freesurfer's Skullstrip program

### ISSUE THREAD

**Issue by luckyxiaoqi** [freesurfer/freesurfer#862] opened 2021-07-28 11:24 UTC

**Comment by ahoopes** [comment] 2021-08-10 04:07
Currently, the default skullstripping (watershed) template used in recon-all is `$FREESURFER_HOME/average/RB_all_withskull_2020_01_02.gca`. Closing as this is not a bug.

**Closed as completed by ahoopes** 2021-08-10 04:07 UTC
